accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('signup/', print_signup, name='signup'),
    path('login/', print_login, name='login'),
    path('logout/', print_logout, name='logout'),
]

config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.urls import include
from preprint.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main, name="main"),
    path('upload/', upload, name="upload"),
    path('guide/', guide, name="guide"),
    path('delete-upload/<int:upload_id>/', delete_upload, name='delete_upload'),
    path('detail/', detail, name="detail"),
    path('accounts/', include('accounts.urls')),
    path('preprint/', include('preprint.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

preprint/urls.py
from django.urls import path
from preprint.views import *

app_name = 'preprint'

urlpatterns = [
    path('mypage/', mypage, name='mypage'),
    path('cloud_history/', cloud_history, name='cloud_history'),
]

templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %} | pre-print</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}?after">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/logo.png' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
    {% block additional_head %}
    {% endblock %}
</head>
<body>
    <div class="navbar">
        <div class="navbar-left">
            <a href="{% url 'main' %}">
                <img class="logo-image" src="{% static 'img/logo2.png' %}" alt="로고">
            </a>
        </div>

        <div class="navbar-right">
            <div class="navbar-center">
                <a class="introduce" href="/guide/">이용방법</a>
            </div>
            <a href="{% url 'preprint:mypage' %}">
                <img class="mypage-image" src="{% static 'img/mypage2.png' %}" alt="로고">
            </a>
            <a href="{% url 'preprint:cloud_history' %}">
                <img class="cloud-image" src="{% static 'img/history.png' %}" alt="로고">
            </a>
        </div>
    </div>
    <div class="content">
        {% block content %}
        {% endblock %}
    </div>
    <div class="footer">
        <p>위치: 서울 서대문구 거북골로 34  명지대학교 학생회관 1층 preprint</p>
        <p>서비스 오류 및 수정 문의: choiet4187@naver.com</p>
    </div>
</body>
</html>

templates/print_detail.html
{% extends 'main.html' %}
{% load static %}
{% block title %}상세 클라우드{% endblock %}

{% block additional_head %}
<link rel="stylesheet" href="{% static 'css/preprint.css' %}?after">
{% endblock %}

{% block content %}
<div class="payment-detail-container">
    <h1 class="logo">Upload File</h1>
    <div class="payment-detail-page">
        {% if upload_with_files %}
            <div class="order-div">
                <h3>등록 번호: {{ upload_with_files.upload.id }}</h3>
                <p>등록 날짜: {{ upload_with_files.upload.upload_date }}</p>
                <div>
                    <p>업로드 PW: {{ upload_with_files.upload.upload_pw }}</p>
                </div>
                <h4>파일:</h4>
                <ul class="order-files">
                    {% for file in upload_with_files.upload_files %}
                        <li><a href="{{ file.upload_file.url }}">{{ file.upload_file.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        {% else %}
            <p>주문 정보를 찾을 수 없습니다.</p>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/print_main.html
{% extends 'main.html' %}
{% load static %}
{% block title %}메인페이지{% endblock %}

{% block content %}
<div class="print-main">
  <h1 class="logo">preprint cloud</h1>
  <form action="/detail/">
    <div class="search-form-group">
      <input class="search-space" type="text" name="cloud_code" placeholder="코드를 입력해주세요." autocomplete="off">
      <button class="search-submit-button" type="submit">
        <i class="fa fa-search"></i>
      </button>
    </div>
  </form>
  {% if messages %}
  {% for message in messages %}
      <p {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
  {% endfor %}
  {% endif %}

  <form action="/upload/">
    <button type="submit" class="print-start-button">upload !</button>
  </form>

  <div class="authentication">
    {% if request.user.is_authenticated %}
    <span>로그인 상태: {{request.user.username}}</span>
    <a href="{% url 'accounts:logout' %}" class="logout-link">로그아웃</a>
    {% else %}
    <span>비로그인 상태</span>
    <a href="{% url 'accounts:login' %}">로그인</a>
    <a href="{% url 'accounts:signup' %}">회원가입</a>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/print_upload.html
{% extends 'main.html' %}
{% load static %}
{% block title %}파일 업로드{% endblock %}
{% block content %}
<div class="centered-form-container">
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <h1 class="logo">file upload</h1>
    <div class="detail-form-group">
      <h2>파일:</h2>
      <input class="file-submit-button" type="file" name="files" multiple>
    </div>

    <div class="detail-form-group">
      <h2>비밀번호:</h2> 
      <input class="pw-space" type="text" name="pw">
    </div>
    <p>업로드 비밀번호는 8자 이상 16자 이하의 문자, 숫자의 조합으로 작성해주세요.</p>
    <p>shift, control키를 통해 여러 파일을 선택할 수 있습니다.</p>
    <button class="pw-submit-button" type="submit">upload!</button>
    {% if messages %}
    <div class="messages">
        {% for message in messages %}
            <p {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
        {% endfor %}
    </div>
    {% endif %}
  </form>
</div>
{% endblock %}